/**
 * initiate-paystack-payment
 *
 * Charges Kenya M-Pesa through Paystack mobile_money for a tenant invoice.
 * For Safaricom Daraja STK use initiate-mpesa-stk-push.
 *
 * SECURITY / RELIABILITY (hardening pass):
 * 1. The invoice is now fetched and verified server-side — previously the
 *    invoiceNumber/amount/tenant relationship were taken verbatim from the
 *    client with no check that invoiceId actually belonged to the caller,
 *    or that amount matched the invoice, or even that a manager_id existed
 *    to credit. A malicious caller could invoke this with any invoiceId.
 * 2. A pending `payment_transactions` row is now created BEFORE contacting
 *    Paystack (mirroring initiate-mpesa-stk-push) so the async
 *    charge.success/charge.failed webhook (paystack-webhook) — and the
 *    reconcile-paystack sweep — have a durable record to reconcile against.
 *    Previously nothing was ever persisted, so a successful Paystack charge
 *    had no way to mark the invoice paid.
 * 3. Our own reference (not Paystack's autogenerated one) is passed to
 *    Paystack so the webhook can look the transaction back up.
 */
import { serve } from "std/http/server.ts";
import { getCorsHeaders, preflightResponse } from "../_shared/cors.ts";
import { checkRateLimit, rateLimitResponse, RATE_LIMITS } from "../_shared/rateLimit.ts";
import { createClient } from "supabase/supabase-js@2";
import { getEnv } from "../_shared/env.ts";
import { chargePaystackMpesa } from "../_shared/paystackMobileMoney.ts";

const logStep = (step: string, details?: unknown) => {
  console.log(`[initiate-paystack-payment] ${step}`, details ?? "");
};

interface PaymentRequest {
  invoiceId: string;
  amount: number;
  phoneNumber: string;
  description?: string;
}

serve(async (req) => {
  if (req.method === "OPTIONS") return preflightResponse(req);

  let pendingTransactionId: string | null = null;

  try {
    const supabaseClient = createClient(getEnv("SUPABASE_URL"), getEnv("SUPABASE_ANON_KEY"));
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) throw new Error("No authorization header provided");

    const token = authHeader.replace("Bearer ", "");
    const { data: userData, error: userError } = await supabaseClient.auth.getUser(token);
    if (userError) throw new Error(`Authentication error: ${userError.message}`);
    const user = userData.user;
    if (!user?.email) throw new Error("User not authenticated or email not available");

    if (!await checkRateLimit(supabaseClient, user.id, "initiate-paystack-payment", RATE_LIMITS["initiate-paystack-payment"])) {
      return rateLimitResponse(req);
    }

    const body: PaymentRequest = await req.json();
    const { invoiceId, amount, phoneNumber, description } = body;

    if (!invoiceId || typeof amount !== "number" || !isFinite(amount) || amount <= 0 || !phoneNumber) {
      throw new Error("invoiceId, a positive amount, and phoneNumber are required");
    }

    // Service-role client for the ownership lookup + pending-transaction
    // write — RLS would otherwise block reading another tenant's invoice
    // (which is exactly the check we need to run) and the insert needs to
    // succeed regardless of the caller's own row-level policies.
    const supabaseAdmin = createClient(getEnv("SUPABASE_URL"), getEnv("SUPABASE_SERVICE_ROLE_KEY"));

    const { data: invoice, error: invoiceError } = await supabaseAdmin
      .from("invoices")
      .select("id, invoice_number, amount, tenant_id, manager_id, unit_id, property_id, status")
      .eq("id", invoiceId)
      .maybeSingle();

    if (invoiceError || !invoice) {
      throw new Error("Invoice not found");
    }
    if (!["pending", "overdue", "partially_paid"].includes(invoice.status)) {
      throw new Error("This invoice is not currently payable");
    }
    if (!invoice.manager_id) {
      throw new Error("Payment configuration error: this invoice has no assigned manager");
    }

    // Verify the caller is the tenant on this invoice.
    const { data: roleRow } = await supabaseAdmin
      .from("user_roles")
      .select("tenant_id")
      .eq("user_id", user.id)
      .eq("role", "tenant")
      .maybeSingle();
    if (!roleRow?.tenant_id || roleRow.tenant_id !== invoice.tenant_id) {
      throw new Error("You are not authorized to pay this invoice");
    }

    if (Math.abs(Math.round(amount) - Math.round(Number(invoice.amount))) > 1) {
      throw new Error(`Amount mismatch: expected KES ${Math.round(Number(invoice.amount))}, received KES ${Math.round(amount)}`);
    }

    let formattedPhone = phoneNumber.replace(/\s+/g, "").replace(/^(\+?254|0)/, "254");
    if (!formattedPhone.startsWith("254")) formattedPhone = "254" + formattedPhone;

    // Create the pending reconciliation record BEFORE contacting Paystack —
    // money must never be requested unless we already have a durable record
    // to reconcile the async result against.
    const reference = crypto.randomUUID();
    const { data: pendingTransaction, error: pendingTransactionError } = await supabaseAdmin
      .from("payment_transactions")
      .insert({
        invoice_id: invoice.id,
        tenant_id: invoice.tenant_id,
        manager_id: invoice.manager_id,
        unit_id: invoice.unit_id ?? null,
        property_id: invoice.property_id ?? null,
        amount: Math.round(amount),
        phone_number: formattedPhone,
        payment_type: "paystack_mpesa",
        payment_method: "paystack_mobile_money",
        status: "pending",
        initiated_at: new Date().toISOString(),
        checkout_request_id: reference,
      })
      .select("id")
      .single();

    if (pendingTransactionError || !pendingTransaction?.id) {
      throw new Error("Could not create the payment reconciliation record. Please try again.");
    }
    pendingTransactionId = pendingTransaction.id;

    const { ok, payload } = await chargePaystackMpesa({
      email: user.email,
      amountKes: amount,
      phoneNumber,
      reference,
      metadata: {
        invoice_id: invoice.id,
        invoice_number: invoice.invoice_number,
        tenant_id: invoice.tenant_id,
        manager_id: invoice.manager_id,
        transaction_id: pendingTransaction.id,
        custom_fields: [
          { display_name: "Invoice Number", variable_name: "invoice_number", value: invoice.invoice_number },
          { display_name: "Description", variable_name: "description", value: description || "Rent Payment" },
        ],
      },
    });

    logStep("Paystack response", payload);
    if (!ok) {
      await supabaseAdmin.rpc("mark_payment_transaction_failed_atomic", {
        p_transaction_id: pendingTransaction.id,
        p_failure_reason: (payload.message as string) || "Paystack charge initiation failed",
      }).catch(() => undefined);
      throw new Error((payload.message as string) || "Failed to initiate Paystack M-Pesa charge");
    }

    const status = (payload.data as { status?: string; reference?: string; display_text?: string } | undefined);
    return new Response(JSON.stringify({
      success: true,
      message: status?.status === "success"
        ? "Payment completed successfully!"
        : "Paystack sent an M-Pesa prompt. Enter your PIN on the phone.",
      reference: status?.reference ?? reference,
      status: status?.status,
      display_text: status?.display_text,
      transactionId: pendingTransaction.id,
    }), {
      headers: { ...getCorsHeaders(req), "Content-Type": "application/json" },
      status: 200,
    });
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    logStep("ERROR", { message: errorMessage });
    return new Response(JSON.stringify({ success: false, error: errorMessage }), {
      headers: { ...getCorsHeaders(req), "Content-Type": "application/json" },
      status: 500,
    });
  }
});
