apiVersion: v1
kind: Secret
metadata:
  name: {{ include "calqulusrms.fullname" . }}-secrets
  labels:
    {{- include "calqulusrms.labels" . | nindent 4 }}
type: Opaque
stringData:
  supabase-url: {{ .Values.secrets.supabaseUrl | quote }}
  supabase-publishable-key: {{ .Values.secrets.supabasePublishableKey | quote }}
  supabase-service-role-key: {{ .Values.secrets.supabaseServiceRoleKey | quote }}
  demo-seed-secret: {{ .Values.secrets.demoSeedSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "calqulusrms.fullname" . }}-mpesa-secrets
  labels:
    {{- include "calqulusrms.labels" . | nindent 4 }}
type: Opaque
stringData:
  mpesa-consumer-key: {{ .Values.secrets.mpesaConsumerKey | quote }}
  mpesa-consumer-secret: {{ .Values.secrets.mpesaConsumerSecret | quote }}
  mpesa-passkey: {{ .Values.secrets.mpesaPasskey | quote }}
  mpesa-shortcode: {{ .Values.secrets.mpesaShortcode | quote }}
