import React, { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CreditCard, Save } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/shared/components/ui/card';
import { Input } from '@/shared/components/ui/input';
import { Label } from '@/shared/components/ui/label';
import { Button } from '@/shared/components/ui/button';
import { Textarea } from '@/shared/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/shared/components/ui/select';
import { useToast } from '@/shared/hooks/use-toast';

export default function AgencyPaymentRoutingPanel({ agencyId }: { agencyId: string }) {
 const { toast }=useToast(); const qc=useQueryClient();
 const [form,setForm]=useState({method:'mpesa_till',label:'Agency rent collection',till:'',paybill:'',bank:'',accountName:'',accountNumber:'',branch:'',instructions:''});
 const {data:account}=useQuery({queryKey:['agency-payment-routing',agencyId],queryFn:async()=>{const {data,error}=await supabase.from('payment_collection_accounts').select('*').eq('agency_id',agencyId).is('property_id',null).is('unit_id',null).is('lease_id',null).is('tenant_id',null).eq('is_active',true).eq('is_default',true).maybeSingle();if(error&&error.code!=='PGRST116')throw error;return data as any;}});
 useEffect(()=>{if(account)setForm({method:account.payment_method,label:account.account_label??'Agency rent collection',till:account.till_number??'',paybill:account.paybill_number??'',bank:account.bank_name??'',accountName:account.bank_account_name??'',accountNumber:account.bank_account_number??'',branch:account.bank_branch??'',instructions:account.payment_instructions??''})},[account]);
 const save=useMutation({mutationFn:async()=>{const {error}=await supabase.rpc('save_payment_collection_account_atomic' as any,{p_id:account?.id??null,p_payload:{agency_id:agencyId,payment_method:form.method,account_label:form.label,till_number:form.till,paybill_number:form.paybill,bank_name:form.bank,bank_account_name:form.accountName,bank_account_number:form.accountNumber,bank_branch:form.branch,payment_instructions:form.instructions,is_default:true,is_active:true,priority:100}});if(error)throw error},onSuccess:()=>{qc.invalidateQueries({queryKey:['agency-payment-routing',agencyId]});toast({title:'Agency payment destination saved'})},onError:(e:Error)=>toast({title:'Could not save payment destination',description:e.message,variant:'destructive'})});
 const set=(k:string)=>(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement>)=>setForm(f=>({...f,[k]:e.target.value}));
 return <Card><CardHeader><CardTitle className="text-sm flex items-center gap-2"><CreditCard className="h-4 w-4"/>Agency-wide payment destination</CardTitle><CardDescription className="text-xs">This is the fallback for properties in this agency. A property or unit configuration always overrides it.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid grid-cols-2 gap-3"><div><Label className="text-xs">Payment method</Label><Select value={form.method} onValueChange={v=>setForm(f=>({...f,method:v}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="mpesa_till">M-Pesa Till</SelectItem><SelectItem value="mpesa_paybill">M-Pesa Paybill</SelectItem><SelectItem value="bank_transfer">Bank transfer</SelectItem><SelectItem value="cash">Cash / office</SelectItem></SelectContent></Select></div><div><Label className="text-xs">Account label</Label><Input value={form.label} onChange={set('label')}/></div></div>{form.method==='mpesa_till'&&<div><Label className="text-xs">Till number</Label><Input value={form.till} onChange={set('till')}/></div>}{form.method==='mpesa_paybill'&&<div><Label className="text-xs">Paybill number</Label><Input value={form.paybill} onChange={set('paybill')}/></div>}{form.method==='bank_transfer'&&<div className="grid grid-cols-2 gap-3"><Input placeholder="Bank name" value={form.bank} onChange={set('bank')}/><Input placeholder="Account name" value={form.accountName} onChange={set('accountName')}/><Input placeholder="Account number" value={form.accountNumber} onChange={set('accountNumber')}/><Input placeholder="Branch" value={form.branch} onChange={set('branch')}/></div>}<div><Label className="text-xs">Tenant instructions</Label><Textarea value={form.instructions} onChange={set('instructions')} placeholder="Payment reference instructions"/></div><div className="flex justify-end"><Button size="sm" onClick={()=>save.mutate()} disabled={save.isPending}><Save className="h-4 w-4 mr-2"/>{save.isPending?'Saving…':'Save agency destination'}</Button></div></CardContent></Card>
}
