from pathlib import Path
p=Path('/mnt/data/nextops2/src/features/dashboard/pages/AccountantDashboard.tsx')
s=p.read_text()
s=s.replace("import { useAuth } from '@/features/auth/AuthContext';", "import { useAuth } from '@/features/auth/AuthContext';\nimport { useManagerScope } from '@/shared/hooks/useManagerScope';")
s=s.replace("  const { user } = useAuth();\n", "  const { user } = useAuth();\n  const { managerId, restrictToAssignedProperties, assignedPropertyIds } = useManagerScope();\n",1)
s=s.replace("      if (!user) return null;", "      if (!user || !managerId) return null;\n      if (restrictToAssignedProperties && assignedPropertyIds.length === 0) {\n        return { pendingInvoices: [], overdueInvoices: [], recentPaidInvoices: [], pendingPayouts: [], properties: [], metrics: { totalPending: 0, totalOverdue: 0, totalCollected: 0, totalPendingPayouts: 0 }, financialTrends: [] };\n      }")
old="""        supabase.from('invoices').select('id, invoice_number, amount, balance_due, due_date, status, tenant_id').eq('status', 'pending').limit(10),
        supabase.from('invoices').select('id, invoice_number, amount, balance_due, due_date, status, tenant_id').eq('status', 'overdue').limit(10),
        supabase.from('invoices').select('id, invoice_number, amount, paid_date, status').eq('status', 'paid').gte('paid_date', startOfMonth(subMonths(new Date(), 5)).toISOString()).order('paid_date', { ascending: false }).limit(1000),
        supabase.from('payout_requests').select('id, amount, status, created_at, property_id').eq('status', 'pending').limit(10),
        supabase.from('properties').select('id, name, occupied, units').limit(10),"""
new="""        (() => { let q = supabase.from('invoices').select('id, invoice_number, amount, balance_due, due_date, status, tenant_id, property_id').eq('manager_id', managerId).eq('status', 'pending').limit(10); if (restrictToAssignedProperties) q = q.in('property_id', assignedPropertyIds); return q; })(),
        (() => { let q = supabase.from('invoices').select('id, invoice_number, amount, balance_due, due_date, status, tenant_id, property_id').eq('manager_id', managerId).eq('status', 'overdue').limit(10); if (restrictToAssignedProperties) q = q.in('property_id', assignedPropertyIds); return q; })(),
        (() => { let q = supabase.from('invoices').select('id, invoice_number, amount, paid_date, status, property_id').eq('manager_id', managerId).eq('status', 'paid').gte('paid_date', startOfMonth(subMonths(new Date(), 5)).toISOString()).order('paid_date', { ascending: false }).limit(1000); if (restrictToAssignedProperties) q = q.in('property_id', assignedPropertyIds); return q; })(),
        (() => { let q = supabase.from('payout_requests').select('id, amount, status, created_at, property_id').eq('manager_id', managerId).eq('status', 'pending').limit(10); if (restrictToAssignedProperties) q = q.in('property_id', assignedPropertyIds); return q; })(),
        (() => { let q = supabase.from('properties').select('id, name, occupied, units').eq('manager_id', managerId); if (restrictToAssignedProperties) q = q.in('id', assignedPropertyIds); return q.limit(10); })(),"""
s=s.replace(old,new)
s=s.replace("Automated reminders have been dispatched.", "Review the overdue queue and follow up on delinquent accounts.")
s=s.replace("Real-time ledger tracking, bank reconciliations, owner disbursements, and accounts receivable controls.", "Ledger tracking, bank reconciliation, owner disbursements, and accounts receivable controls.")
s=s.replace("            Export General Ledger", "            Open Financial Records")
s=s.replace("          <Download className=\"h-3.5 w-3.5\" />\n            Open Financial Records", "          <Download className=\"h-3.5 w-3.5\" />\n            Open Financial Records")
# make button honest and actionable
s=s.replace('<Button size="sm" className="gap-1.5 h-9 font-semibold">\n            <Download className="h-3.5 w-3.5" />\n            Open Financial Records\n          </Button>', '<Button size="sm" className="gap-1.5 h-9 font-semibold" onClick={() => window.location.href = \'/billing\'}>\n            <Download className="h-3.5 w-3.5" />\n            Open Financial Records\n          </Button>')
p.write_text(s)

p=Path('/mnt/data/nextops2/src/features/dashboard/pages/MaintenanceDashboard.tsx')
s=p.read_text()
s=s.replace("import { useAuth } from '@/features/auth/AuthContext';", "import { useAuth } from '@/features/auth/AuthContext';\nimport { useManagerScope } from '@/shared/hooks/useManagerScope';")
s=s.replace("  const { user } = useAuth();\n", "  const { user } = useAuth();\n  const { managerId, restrictToAssignedProperties, assignedPropertyIds } = useManagerScope();\n",1)
s=s.replace("      if (!user) return null;", "      if (!user || !managerId) return null;\n      if (restrictToAssignedProperties && assignedPropertyIds.length === 0) return { allRequests: [], urgentRequests: [], metrics: { pendingCount: 0, inProgressCount: 0, urgentCount: 0, completedCount: 0, avgDispatchHours: null } };")
s=s.replace("        supabase.from('maintenance_requests').select('id, title, priority, status, created_at, unit_id, description, provider_started_at, completion_date').order('created_at', { ascending: false }).limit(20),\n        supabase.from('maintenance_requests').select('id, title, priority, status, created_at').eq('priority', 'urgent').neq('status', 'completed'),\n        supabase.from('maintenance_requests').select('id').eq('status', 'in_progress'),\n        supabase.from('maintenance_requests').select('id, created_at, provider_started_at, completion_date').gte('created_at', subDays(new Date(), 90).toISOString()).eq('status', 'completed'),", "        (() => { let q = supabase.from('maintenance_requests').select('id, title, priority, status, created_at, unit_id, description, provider_started_at, completion_date, manager_id').eq('manager_id', managerId).order('created_at', { ascending: false }).limit(20); if (restrictToAssignedProperties) q = q.in('unit_id', assignedPropertyIds); return q; })(),\n        supabase.from('maintenance_requests').select('id, title, priority, status, created_at, manager_id').eq('manager_id', managerId).eq('priority', 'urgent').neq('status', 'completed'),\n        supabase.from('maintenance_requests').select('id, manager_id').eq('manager_id', managerId).eq('status', 'in_progress'),\n        supabase.from('maintenance_requests').select('id, created_at, provider_started_at, completion_date, manager_id').eq('manager_id', managerId).gte('created_at', subDays(new Date(), 90).toISOString()).eq('status', 'completed'),")
s=s.replace("(dispatch priority: urgent).", "(priority: urgent).")
p.write_text(s)

p=Path('/mnt/data/nextops2/src/features/dashboard/pages/LeasingDashboard.tsx')
s=p.read_text()
s=s.replace("import { useAuth } from '@/features/auth/AuthContext';", "import { useAuth } from '@/features/auth/AuthContext';\nimport { useManagerScope } from '@/shared/hooks/useManagerScope';")
s=s.replace("  const { user } = useAuth();\n", "  const { user } = useAuth();\n  const { managerId, restrictToAssignedProperties, assignedPropertyIds } = useManagerScope();\n",1)
s=s.replace("      if (!user) return null;", "      if (!user || !managerId) return null;\n      if (restrictToAssignedProperties && assignedPropertyIds.length === 0) return { expiringLeases: [], pendingInvites: [], metrics: { totalUnits: 0, totalOccupied: 0, vacantUnits: 0, occupancyRate: 0, activeLeaseCount: 0, expiringCount: 0, pendingInviteCount: 0 } };")
s=s.replace("        supabase.from('leases').select('id, monthly_rent, status, start_date, end_date').eq('status', 'active'),\n        supabase.from('leases').select('id, monthly_rent, status, end_date, unit').eq('status', 'expiring').limit(10),\n        supabase.from('properties').select('id, name, units, occupied'),\n        supabase.from('tenant_invitations').select('id, email, name, created_at, status').eq('status', 'pending').limit(10),", "        (() => { let q = supabase.from('leases').select('id, monthly_rent, status, start_date, end_date, property_id').eq('status', 'active'); if (restrictToAssignedProperties) q = q.in('property_id', assignedPropertyIds); return q; })(),\n        (() => { let q = supabase.from('leases').select('id, monthly_rent, status, end_date, unit, property_id').eq('status', 'expiring').limit(10); if (restrictToAssignedProperties) q = q.in('property_id', assignedPropertyIds); return q; })(),\n        (() => { let q = supabase.from('properties').select('id, name, units, occupied').eq('manager_id', managerId); if (restrictToAssignedProperties) q = q.in('id', assignedPropertyIds); return q; })(),\n        (() => { let q = supabase.from('tenant_invitations').select('id, email, tenant_name, created_at, status, property_id').eq('invited_by', managerId).eq('status', 'pending').limit(10); if (restrictToAssignedProperties) q = q.in('property_id', assignedPropertyIds); return q; })(),")
s=s.replace("subtitle=\"Renewal offers ready\"", "subtitle=\"Review renewal or move-out action\"")
s=s.replace("Send Renewal", "Review Lease")
p.write_text(s)

# Add truthfulness/scope regression test
p=Path('/mnt/data/nextops2/src/test/operationalScopeIntegrity.test.ts')
p.write_text('''import { describe, expect, it } from "vitest";\nimport { readFileSync } from "node:fs";\n\nconst read = (path: string) => readFileSync(path, "utf8");\n\ndescribe("operational command-center scope integrity", () => {\n  it("scopes accountant dashboard financial queries to the manager", () => {\n    const source = read("src/features/dashboard/pages/AccountantDashboard.tsx");\n    expect(source).toContain("eq('manager_id', managerId)");\n    expect(source).toContain("assignedPropertyIds");\n    expect(source).not.toContain("Automated reminders have been dispatched.");\n  });\n\n  it("scopes maintenance dashboard requests to the manager", () => {\n    const source = read("src/features/dashboard/pages/MaintenanceDashboard.tsx");\n    expect(source).toContain("eq('manager_id', managerId)");\n    expect(source).toContain("useManagerScope");\n  });\n\n  it("scopes leasing dashboard properties and lease queues", () => {\n    const source = read("src/features/dashboard/pages/LeasingDashboard.tsx");\n    expect(source).toContain("eq('manager_id', managerId)");\n    expect(source).toContain("property_id', assignedPropertyIds");\n    expect(source).not.toContain('change=\"+2.5%\"');\n  });\n});\n''')
