import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { BarChart3, BookOpen, FileText, ShieldCheck, TriangleAlert } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useManagerScope } from "@/shared/hooks/useManagerScope";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/shared/components/ui/card";
import { Badge } from "@/shared/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/shared/components/ui/select";

const TrialBalanceFinancialStatementsCenter = () => {
  const { managerId } = useManagerScope();
  const [periodId, setPeriodId] = useState("");
  const { data: periods = [] } = useQuery({
    queryKey: ["financial-statement-periods", managerId], enabled: !!managerId,
    queryFn: async () => { const { data, error } = await supabase.from("financial_close_periods").select("id,period_start,period_end,status").eq("manager_id", managerId!).order("period_end", { ascending: false }).limit(24); if (error) throw error; return data ?? []; },
  });
  const period = periods.find((p: any) => p.id === periodId);
  const periodStart = period?.period_start;
  const periodEnd = period?.period_end;
  const { data: tb } = useQuery({ queryKey: ["trial-balance", managerId, period?.id], enabled: !!managerId && !!period, queryFn: async () => { const { data,error }=await supabase.rpc("get_manager_trial_balance",{p_manager_id:managerId!,p_period_start:periodStart!,p_period_end:periodEnd!}); if(error)throw error; return data as any; } });
  const { data: fs } = useQuery({ queryKey: ["financial-statements", managerId, period?.id], enabled: !!managerId && !!period, queryFn: async () => { const { data,error }=await supabase.rpc("get_manager_financial_statements",{p_manager_id:managerId!,p_period_start:periodStart!,p_period_end:periodEnd!}); if(error)throw error; return data as any; } });
  const { data: gl } = useQuery({ queryKey: ["general-ledger", managerId, period?.id], enabled: !!managerId && !!period, queryFn: async () => { const { data,error }=await supabase.rpc("get_manager_general_ledger",{p_manager_id:managerId!,p_period_start:periodStart!,p_period_end:periodEnd!,p_account_id:null}); if(error)throw error; return data as any; } });
  const fmt = (v: any) => Number(v ?? 0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
  const pnl=fs?.profit_and_loss; const bs=fs?.balance_sheet;
  return <Card className="enterprise-card"><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="section-title flex items-center gap-2"><BarChart3 className="h-5 w-5"/> Trial Balance & Financial Statements</CardTitle><CardDescription>Management reporting derived from posted double-entry journals, with no parallel accounting source.</CardDescription></div><Badge variant="outline" className="gap-1"><ShieldCheck className="h-3 w-3"/> Journal-derived</Badge></div></CardHeader><CardContent className="space-y-5">
    <Select value={periodId} onValueChange={setPeriodId}><SelectTrigger><SelectValue placeholder="Select an accounting period"/></SelectTrigger><SelectContent>{periods.map((p:any)=><SelectItem key={p.id} value={p.id}>{p.period_start} → {p.period_end} · {p.status}</SelectItem>)}</SelectContent></Select>
    {!period && <p className="text-sm text-muted-foreground">Select a period to produce controlled accounting reports.</p>}
    {period && <>
      <div className="grid gap-3 md:grid-cols-4"><div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">Trial balance debits</p><p className="font-semibold tabular-nums">{fmt(tb?.totals?.debits)}</p></div><div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">Trial balance credits</p><p className="font-semibold tabular-nums">{fmt(tb?.totals?.credits)}</p></div><div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">Net income</p><p className="font-semibold tabular-nums">{fmt(pnl?.net_income)}</p></div><div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">Balance-sheet difference</p><p className="font-semibold tabular-nums">{fmt((bs?.total_assets ?? 0)-((bs?.total_liabilities ?? 0)+(bs?.total_equity ?? 0)))}</p></div></div>
      <div className="rounded-lg border p-4"><div className="mb-3 flex items-center justify-between"><p className="font-semibold flex items-center gap-2"><BookOpen className="h-4 w-4"/> Trial balance</p><Badge variant={(tb?.totals?.balance_difference ?? 0) === 0 ? "default" : "destructive"}>{(tb?.totals?.balance_difference ?? 0) === 0 ? "Balanced" : <><TriangleAlert className="mr-1 h-3 w-3"/> Out of balance</>}</Badge></div><div className="space-y-2">{(tb?.rows ?? []).map((r:any)=><div key={r.id} className="grid grid-cols-[90px_1fr_120px_120px] gap-2 border-b py-2 text-sm last:border-0"><span>{r.account_code}</span><span>{r.account_name}</span><span className="text-right tabular-nums">{fmt(r.debits)}</span><span className="text-right tabular-nums">{fmt(r.credits)}</span></div>)}</div></div>
      <div className="rounded-lg border p-4"><p className="mb-3 font-semibold flex items-center gap-2"><BookOpen className="h-4 w-4"/> General ledger activity</p><div className="space-y-2">{(gl?.entries ?? []).slice(0,20).map((e:any)=><div key={e.id} className="rounded-md border p-3 text-sm"><div className="flex justify-between gap-3"><span className="font-medium">{e.entry_date} · {e.description}</span><span className="text-xs text-muted-foreground">{e.source_type}</span></div><div className="mt-2 space-y-1">{(e.lines ?? []).map((l:any)=><div key={l.id} className="grid grid-cols-[70px_1fr_100px_100px] gap-2 text-xs"><span>{l.account_code}</span><span>{l.account_name}</span><span className="text-right tabular-nums">{fmt(l.debit)}</span><span className="text-right tabular-nums">{fmt(l.credit)}</span></div>)}</div></div>)}{!(gl?.entries?.length) && <p className="text-sm text-muted-foreground">No posted journal activity in this period.</p>}</div></div>
      <div className="grid gap-4 lg:grid-cols-2"><div className="rounded-lg border p-4"><p className="mb-3 font-semibold flex items-center gap-2"><FileText className="h-4 w-4"/> Profit & loss</p><p className="text-sm">Income <span className="float-right tabular-nums">{fmt(pnl?.total_income)}</span></p><p className="text-sm">Expenses <span className="float-right tabular-nums">{fmt(pnl?.total_expenses)}</span></p><p className="mt-2 border-t pt-2 font-semibold">Net income <span className="float-right tabular-nums">{fmt(pnl?.net_income)}</span></p></div><div className="rounded-lg border p-4"><p className="mb-3 font-semibold flex items-center gap-2"><FileText className="h-4 w-4"/> Balance sheet</p><p className="text-sm">Assets <span className="float-right tabular-nums">{fmt(bs?.total_assets)}</span></p><p className="text-sm">Liabilities <span className="float-right tabular-nums">{fmt(bs?.total_liabilities)}</span></p><p className="text-sm">Equity + current earnings <span className="float-right tabular-nums">{fmt(bs?.total_equity)}</span></p><p className="mt-2 border-t pt-2 text-xs text-muted-foreground">Current-period earnings are presented as the derived equity bridge because the journal model does not introduce a duplicate retained-earnings source.</p></div></div>
    </>}
  </CardContent></Card>;
};
export default TrialBalanceFinancialStatementsCenter;
