import React, { useEffect, useMemo, useState } from 'react';
import { useParams } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/shared/components/ui/card';
import { Checkbox } from '@/shared/components/ui/checkbox';
import { Input } from '@/shared/components/ui/input';
import { Label } from '@/shared/components/ui/label';
import { Button } from '@/shared/components/ui/button';
import { Badge } from '@/shared/components/ui/badge';
import { Loader2, Smartphone, CheckCircle2, ShieldCheck } from 'lucide-react';

const money=(n:number)=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES',maximumFractionDigits:0}).format(n);
export default function PublicPaymentShare(){
 const {token=''}=useParams(); const [rows,setRows]=useState<any[]>([]); const [selected,setSelected]=useState<string[]>([]); const [name,setName]=useState(''); const [phone,setPhone]=useState(''); const [code,setCode]=useState(''); const [grant,setGrant]=useState(''); const [loading,setLoading]=useState(true); const [verified,setVerified]=useState(false); const [busy,setBusy]=useState(false); const [txId,setTxId]=useState<string|null>(null); const [status,setStatus]=useState<any>(null); const [error,setError]=useState('');
 const verify=async()=>{setBusy(true);setError('');try{const {data,error}=await supabase.rpc('verify_public_payment_share',{p_token:token,p_access_code:code});if(error||!data?.grant)throw new Error(error?.message||'Invalid access code');const g=String(data.grant);setGrant(g);sessionStorage.setItem(`calqulus-share:${token}`,g);const {data:share,error:shareError}=await supabase.rpc('get_public_payment_share',{p_token:token,p_grant:g});if(shareError||!share?.length)throw new Error('This payment link is unavailable or has expired.');setRows(share);setSelected(share.filter((r:any)=>Number(r.balance_due)>0).map((r:any)=>r.invoice_id));setVerified(true);}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 useEffect(()=>{let live=true;const saved=sessionStorage.getItem(`calqulus-share:${token}`);if(saved){(async()=>{const {data,error}=await supabase.rpc('get_public_payment_share',{p_token:token,p_grant:saved});if(live&&data?.length&&!error){setGrant(saved);setRows(data);setSelected(data.filter((r:any)=>Number(r.balance_due)>0).map((r:any)=>r.invoice_id));setVerified(true)}setLoading(false)})()}else setLoading(false);return()=>{live=false}},[token]);
 const selectedRows=rows.filter(r=>selected.includes(r.invoice_id)&&Number(r.balance_due)>0); const total=useMemo(()=>selectedRows.reduce((s,r)=>s+Number(r.balance_due),0),[selectedRows]);
 useEffect(()=>{if(!txId)return;let stopped=false;const poll=async()=>{const {data}=await supabase.rpc('get_public_payment_share_status',{p_token:token,p_transaction_id:txId,p_grant:grant});if(!stopped&&data){setStatus(data);if(!['completed','failed','cancelled'].includes(data.status))setTimeout(poll,4000)}};void poll();return()=>{stopped=true}},[token,txId,grant]);
 const pay=async()=>{setBusy(true);setError('');try{const normalized=phone.replace(/\D/g,'');const formatted=normalized.startsWith('0')?'254'+normalized.slice(1):normalized.startsWith('254')?normalized:'254'+normalized;const {data,error}=await supabase.functions.invoke('initiate-shared-payment',{body:{token,accessGrant:grant,invoiceIds:selectedRows.map(r=>r.invoice_id),amount:total,phoneNumber:formatted,payerName:name}});if(error||!data?.transactionId)throw new Error(data?.error||error?.message||'Could not start payment');setTxId(data.transactionId)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 if(loading)return <div className="min-h-screen grid place-items-center p-4"><Loader2 className="h-8 w-8 animate-spin"/></div>;
 if(!verified)return <div className="min-h-screen grid place-items-center bg-muted/20 p-4"><Card className="max-w-md w-full"><CardHeader className="text-center"><ShieldCheck className="h-12 w-12 mx-auto mb-2"/><CardTitle>Secure payment access</CardTitle><CardDescription>This shared link is protected. The access code must be provided separately by the tenant. No tenant name, phone number or bill details are shown before verification.</CardDescription></CardHeader><CardContent className="space-y-4"><div><Label>One-time access code</Label><Input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="6-digit code" inputMode="numeric" /></div>{error&&<p className="text-sm text-destructive">{error}</p>}<Button className="w-full" onClick={()=>void verify()} disabled={busy||code.length!==6}>{busy?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<ShieldCheck className="mr-2 h-4 w-4"/>}{busy?'Verifying…':'Open secure payment'}</Button></CardContent></Card></div>;
 if(error&&!rows.length)return <div className="min-h-screen grid place-items-center p-4"><Card className="max-w-md w-full"><CardHeader><CardTitle>Payment link unavailable</CardTitle><CardDescription>{error}</CardDescription></CardHeader></Card></div>;
 if(status?.status==='completed')return <div className="min-h-screen grid place-items-center p-4"><Card className="max-w-md w-full"><CardHeader className="text-center"><CheckCircle2 className="h-14 w-14 mx-auto text-success"/><CardTitle>Payment received</CardTitle><CardDescription>{money(Number(status.amount))} has been recorded.</CardDescription></CardHeader><CardContent className="space-y-2 text-sm"><div className="rounded-lg border p-3 flex justify-between"><span>Receipt</span><b>{status.receipt?.receipt_number||status.mpesa_receipt_number||'Processing'}</b></div><p className="text-muted-foreground text-center">The tenant and property team can see the allocation automatically.</p></CardContent></Card></div>;
 return <div className="min-h-screen bg-muted/20 p-4 md:p-8"><div className="mx-auto max-w-3xl space-y-5"><div><p className="text-sm text-muted-foreground">CALQULUS PMS</p><h1 className="text-2xl font-bold">Authorized payment</h1><p className="text-sm text-muted-foreground">You are viewing bills through a tenant-authorized payment grant.</p></div><Card><CardHeader><CardTitle>{rows[0]?.label||'Bills to pay'}</CardTitle><CardDescription>Choose the bills you want to cover. Personal tenant contact details are never displayed.</CardDescription></CardHeader><CardContent className="space-y-3">{rows.map((r:any)=><label key={r.invoice_id} className="flex items-center gap-3 rounded-lg border p-4 cursor-pointer"><Checkbox checked={selected.includes(r.invoice_id)} disabled={Number(r.balance_due)<=0} onCheckedChange={v=>setSelected(s=>v?s.includes(r.invoice_id)?s:[...s,r.invoice_id]:s.filter(x=>x!==r.invoice_id))}/><div className="flex-1"><div className="flex items-center gap-2"><b>Unit {r.unit_number}</b><Badge variant={r.status==='overdue'?'destructive':'secondary'}>{r.status}</Badge></div><p className="text-xs text-muted-foreground">{r.property_name} · Due {r.due_date}</p></div><b>{money(Number(r.balance_due))}</b></label>)}{selectedRows.length>0&&!txId&&<div className="rounded-xl border bg-card p-4 space-y-4"><div><p className="text-xs text-muted-foreground">Selected total</p><p className="text-2xl font-bold">{money(total)}</p></div><div className="grid gap-3 md:grid-cols-2"><div><Label>Your name</Label><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Payer name"/></div><div><Label>M-Pesa number</Label><Input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="0712 345 678"/></div></div>{error&&<p className="text-sm text-destructive">{error}</p>}<Button className="w-full" onClick={pay} disabled={busy||!name.trim()||!phone.trim()}>{busy?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Smartphone className="mr-2 h-4 w-4"/>}{busy?'Sending prompt…':`Pay ${money(total)} by M-Pesa`}</Button></div>}{txId&&status?.status==='pending'&&<div className="rounded-xl border bg-primary/5 p-5 text-center space-y-2"><Smartphone className="h-8 w-8 mx-auto"/><b>Check your phone</b><p className="text-sm text-muted-foreground">Complete the M-Pesa prompt. We are checking the payment automatically.</p></div>}<div className="flex items-center justify-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="h-3 w-3"/>Access is protected by a short-lived authorization grant</div></CardContent></Card></div></div>;
}
