import React,{useState} from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/shared/components/ui/button';
import { Input } from '@/shared/components/ui/input';
import { Label } from '@/shared/components/ui/label';
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from '@/shared/components/ui/dialog';
import { Share2,Copy,Loader2,Link2,ShieldCheck } from 'lucide-react';
import { useToast } from '@/shared/hooks/use-toast';

export default function TenantPaymentShareButton(){
 const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false); const [link,setLink]=useState(''); const [code,setCode]=useState(''); const [hours,setHours]=useState('168'); const [recipient,setRecipient]=useState(''); const {toast}=useToast();
 const create=async()=>{setBusy(true);try{const {data,error}=await supabase.rpc('create_tenant_payment_share_link_atomic',{p_invoice_ids:null,p_expires_in_hours:Number(hours),p_label:'Shared bills',p_recipient_label:recipient||null});if(error)throw error;setLink(`${window.location.origin}/pay/${data.token}`);setCode(String(data.access_code||''));}catch(e:any){toast({title:'Could not create payment link',description:e.message,variant:'destructive'})}finally{setBusy(false)}};
 const copy=async()=>{await navigator.clipboard.writeText(link);toast({title:'Link copied',description:'Send the access code separately to the authorized payer.'})};
 const share=async()=>{if(navigator.share)await navigator.share({title:'CALQULUS payment link',text:'Please use this secure link to pay my bills. I will send the access code separately.',url:link});else await copy()};
 return <><Button variant="outline" className="gap-2" onClick={()=>{setLink('');setCode('');setRecipient('');setOpen(true)}}><Share2 className="h-4 w-4"/>Share payment link</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Share bills securely</DialogTitle><DialogDescription>The link alone reveals nothing useful. Give the link and the separate one-time access code only to the intended parent, guardian or payer.</DialogDescription></DialogHeader><div className="space-y-4"><div><Label>Authorized recipient (optional)</Label><Input value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder="e.g. Mum / Dad / Sponsor" disabled={!!link}/></div><div><Label>Link expiry</Label><select className="mt-1 w-full h-10 rounded-md border bg-background px-3 text-sm" value={hours} onChange={e=>setHours(e.target.value)} disabled={!!link}><option value="24">24 hours</option><option value="72">3 days</option><option value="168">7 days</option><option value="720">30 days</option></select></div>{link?<><div className="rounded-lg border p-3 space-y-2"><div className="flex items-center gap-2 text-sm font-medium"><ShieldCheck className="h-4 w-4"/>Share these separately</div><div className="flex items-center gap-2"><Link2 className="h-4 w-4 text-muted-foreground shrink-0"/><Input value={link} readOnly/><Button variant="outline" onClick={()=>void copy()}><Copy className="h-4 w-4"/></Button></div><div><p className="text-xs text-muted-foreground">Access code</p><p className="text-2xl font-mono font-bold tracking-[0.35em]">{code}</p></div></div><p className="text-xs text-muted-foreground">Do not post the link and code together publicly. Revoke the link from your payment history if you sent it to the wrong person.</p></>:<Button className="w-full" onClick={()=>void create()} disabled={busy}>{busy?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Link2 className="mr-2 h-4 w-4"/>}{busy?'Creating secure link…':'Create secure payment link'}</Button>}</div><DialogFooter>{link&&<Button onClick={()=>void share()} className="gap-2"><Share2 className="h-4 w-4"/>Share secure link</Button>}</DialogFooter></DialogContent></Dialog></>;
}
