// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
export type { Database };

// Generated Database is still incomplete vs supabase-js GenericSchema, so
// createClient<Database> makes .from()/.rpc() resolve to `never`. Keep Database
// for explicit table types; loosen the runtime client until live `gen types`.
export type AppSupabaseClient = SupabaseClient<any>;

// Use a placeholder default so the app boots in preview mode when env vars
// are absent. The real project URL must come from VITE_SUPABASE_URL — never
// commit it here (the production audit forbids hardcoded Supabase URLs).
const DEFAULT_SUPABASE_URL = "https://placeholder.supabase.co";
const DEFAULT_SUPABASE_ANON_KEY = "ci-placeholder-anon-key";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || DEFAULT_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || DEFAULT_SUPABASE_ANON_KEY;

const isPlaceholderUrl = !SUPABASE_URL || 
  SUPABASE_URL.includes("example.supabase.co") || 
  SUPABASE_URL.includes("your-project.supabase.co") || 
  SUPABASE_URL.includes("placeholder");

const isPlaceholderKey = !SUPABASE_PUBLISHABLE_KEY || 
  SUPABASE_PUBLISHABLE_KEY.includes("ci-placeholder") || 
  SUPABASE_PUBLISHABLE_KEY.includes("your-anon-key") || 
  SUPABASE_PUBLISHABLE_KEY.includes("placeholder");

const MISSING_ENV = isPlaceholderUrl || isPlaceholderKey;
if (MISSING_ENV) {
  console.warn(
    '%c[CALQULUS PMS] Missing or placeholder Supabase env vars (VITE_SUPABASE_URL, VITE_SUPABASE_PUBLISHABLE_KEY).\n' +
    '  The app will load in preview mode with simulated client state.\n' +
    '  Copy .env.example to .env.local and fill in your Supabase project values for live backend sync.',
    'color: #eab308; font-weight: bold'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// ── Remember-me storage toggle ───────────────────────────────────────
// The "Remember me" checkbox on each portal's login screen controls whether
// the Supabase session survives closing the browser tab (localStorage) or
// is cleared when the tab closes (sessionStorage). The preference itself is
// kept in localStorage — it's a tiny, non-sensitive flag, and it must
// survive the full-page navigation to Google and back during OAuth sign-in,
// which a sessionStorage-only flag would risk losing on some browsers.
const REMEMBER_ME_KEY = 'calqulusrms_remember_me';

export function setRememberMe(remember: boolean): void {
  try {
    localStorage.setItem(REMEMBER_ME_KEY, remember ? '1' : '0');
  } catch {
    // localStorage unavailable (private mode, etc.) — falls back to the
    // default (remember = true) below, which is the safest assumption.
  }
}

export function getRememberMe(): boolean {
  try {
    const raw = localStorage.getItem(REMEMBER_ME_KEY);
    return raw === null ? true : raw === '1';
  } catch {
    return true;
  }
}

function activeStore(): Pick<Storage, 'getItem' | 'setItem' | 'removeItem' | 'length' | 'key' | 'clear'> {
  return getRememberMe() ? localStorage : sessionStorage;
}

const safeStorage: Storage = {
  getItem: (k: string) => { try { return activeStore().getItem(k); } catch { return null; } },
  setItem: (k: string, v: string) => { try { activeStore().setItem(k, v); } catch {} },
  removeItem: (k: string) => { try { activeStore().removeItem(k); } catch {} },
  get length() { try { return activeStore().length; } catch { return 0; } },
  key: (i: number) => { try { return activeStore().key(i); } catch { return null; } },
  clear: () => { try { activeStore().clear(); } catch {} },
};

function createNoopProxy(): AppSupabaseClient {
  const baseNoopAuth = {
    onAuthStateChange: () => ({
      data: {
        subscription: {
          unsubscribe: () => {},
        },
      },
    }),
    getSession: () => Promise.resolve({ data: { session: null }, error: null }),
    getUser: () => Promise.resolve({ data: { user: null }, error: null }),
    signInWithPassword: () => Promise.resolve({ data: { user: null, session: null }, error: { message: "Supabase is not configured" } }),
    signUp: () => Promise.resolve({ data: { user: null, session: null }, error: { message: "Supabase is not configured" } }),
    resetPasswordForEmail: () => Promise.resolve({ data: {}, error: { message: "Supabase is not configured" } }),
    setSession: () => Promise.resolve({ data: { user: null, session: null }, error: { message: "Supabase is not configured" } }),
    signOut: () => Promise.resolve({ error: null }),
    updateUser: () => Promise.resolve({ data: { user: null }, error: { message: "Supabase is not configured" } }),
  };

  const noopAuth = new Proxy(baseNoopAuth, {
    get(target, prop) {
      if (prop in target) {
        return (target as Record<string | symbol, unknown>)[prop];
      }
      return () => Promise.resolve({ data: { user: null, session: null }, error: { message: "Supabase is not configured" } });
    },
  });
  interface NoopBuilder extends PromiseLike<{ data: never[]; error: null }> {
    select(...args: unknown[]): NoopBuilder;
    insert(...args: unknown[]): NoopBuilder;
    update(...args: unknown[]): NoopBuilder;
    upsert(...args: unknown[]): NoopBuilder;
    delete(...args: unknown[]): NoopBuilder;
    eq(...args: unknown[]): NoopBuilder;
    neq(...args: unknown[]): NoopBuilder;
    gt(...args: unknown[]): NoopBuilder;
    gte(...args: unknown[]): NoopBuilder;
    lt(...args: unknown[]): NoopBuilder;
    lte(...args: unknown[]): NoopBuilder;
    like(...args: unknown[]): NoopBuilder;
    ilike(...args: unknown[]): NoopBuilder;
    is(...args: unknown[]): NoopBuilder;
    in(...args: unknown[]): NoopBuilder;
    contains(...args: unknown[]): NoopBuilder;
    containedBy(...args: unknown[]): NoopBuilder;
    range(...args: unknown[]): NoopBuilder;
    textSearch(...args: unknown[]): NoopBuilder;
    not(...args: unknown[]): NoopBuilder;
    or(...args: unknown[]): NoopBuilder;
    and(...args: unknown[]): NoopBuilder;
    filter(...args: unknown[]): NoopBuilder;
    match(...args: unknown[]): NoopBuilder;
    order(...args: unknown[]): NoopBuilder;
    limit(...args: unknown[]): NoopBuilder;
    single(...args: unknown[]): NoopBuilder;
    maybeSingle(...args: unknown[]): NoopBuilder;
    csv(...args: unknown[]): NoopBuilder;
    returns(...args: unknown[]): NoopBuilder;
    throwOnError(...args: unknown[]): NoopBuilder;
    abortSignal(...args: unknown[]): NoopBuilder;
  }

  // Chainable noop query builder.
  // Reads resolve to empty data so preview UI can render.
  // Writes resolve with an error so the UI cannot claim a successful persist.
  function createNoopBuilder(kind: 'read' | 'write' = 'read'): NoopBuilder {
    const notConfigured = { message: "Supabase is not configured" };
    const writeOps = new Set(['insert', 'update', 'upsert', 'delete']);
    // Built as a plain record because the chain methods below are attached
    // dynamically in a loop; the object only satisfies the NoopBuilder shape
    // once that loop has run, so the cast to NoopBuilder happens at the end.
    const builder: Record<string, unknown> = {
      then<R>(resolve: (value: { data: never[]; error: null } | { data: null; error: { message: string } }) => R) {
        if (kind === 'write') {
          return Promise.resolve({ data: null, error: notConfigured }).then(resolve as (value: { data: null; error: { message: string } }) => R);
        }
        return Promise.resolve({ data: [], error: null }).then(resolve as (value: { data: never[]; error: null }) => R);
      },
    };
    const chainMethods = [
      'select', 'insert', 'update', 'upsert', 'delete',
      'eq', 'neq', 'gt', 'gte', 'lt', 'lte', 'like', 'ilike',
      'is', 'in', 'contains', 'containedBy', 'range', 'textSearch',
      'not', 'or', 'and', 'filter', 'match',
      'order', 'limit', 'single', 'maybeSingle',
      'csv', 'returns', 'throwOnError', 'abortSignal',
    ];
    for (const m of chainMethods) {
      builder[m] = () => createNoopBuilder(writeOps.has(m) || kind === 'write' ? 'write' : 'read');
    }
    return builder as unknown as NoopBuilder;
  }

  const noopFunctions = {
    invoke: () => Promise.resolve({ data: null, error: { message: "Supabase is not configured" } }),
  };

  const noopStorage = {
    from: () => ({
      upload: () => Promise.resolve({ data: null, error: { message: "Supabase is not configured" } }),
      download: () => Promise.resolve({ data: null, error: { message: "Supabase is not configured" } }),
      remove: () => Promise.resolve({ data: [], error: { message: "Supabase is not configured" } }),
      list: () => Promise.resolve({ data: [], error: null }),
      getPublicUrl: (path: string) => ({ data: { publicUrl: path } }),
    }),
  };

  const noop = new Proxy({}, {
    get(_target, prop) {
      if (prop === 'then' || prop === 'catch' || prop === 'finally') return undefined;
      if (prop === 'auth') return noopAuth;
      if (prop === 'functions') return noopFunctions;
      if (prop === 'storage') return noopStorage;
      if (prop === 'from') {
        return () => createNoopBuilder('read');
      }
      if (prop === 'rpc') {
        return () => createNoopBuilder('write');
      }
      if (prop === 'channel') {
        return () => {
          const mockChannel = {
            on: () => mockChannel,
            subscribe: () => mockChannel,
            unsubscribe: () => {},
            send: () => {},
            track: () => {},
            untrack: () => {},
          };
          return mockChannel;
        };
      }
      if (prop === 'removeChannel' || prop === 'removeAllChannels') {
        return () => {};
      }
      return typeof prop === 'string'
        ? () => createNoopBuilder()
        : noop;
    },
  });
  return noop as unknown as AppSupabaseClient;
}

function initSupabaseClient(): AppSupabaseClient {
  if (MISSING_ENV) {
    return createNoopProxy();
  }
  try {
    return createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: safeStorage,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
      }
    }) as AppSupabaseClient;
  } catch (err) {
    console.warn('[CALQULUS PMS] Failed to create Supabase client, falling back to proxy:', err);
    return createNoopProxy();
  }
}

export const supabase: AppSupabaseClient = initSupabaseClient();
