import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, ClipboardList, RefreshCw } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useManagerScope } from "@/shared/hooks/useManagerScope";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/shared/components/ui/card";
import { Input } from "@/shared/components/ui/input";
import { Button } from "@/shared/components/ui/button";
import { Badge } from "@/shared/components/ui/badge";
import { toast } from "sonner";

const fmt=(v:unknown)=>Number(v??0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});

export default function ExpenseCommitmentPayablesCenter(){
  const {managerId}=useManagerScope();
  const [vendor,setVendor]=useState(""); const [category,setCategory]=useState(""); const [amount,setAmount]=useState(""); const [due,setDue]=useState(new Date().toISOString().slice(0,10)); const [description,setDescription]=useState("");
  const q=useQuery({queryKey:["expense-commitments",managerId],enabled:!!managerId,queryFn:async()=>{const {data,error}=await supabase.rpc("get_manager_expense_commitment_control",{p_manager_id:managerId!,p_as_of_date:new Date().toISOString().slice(0,10),p_horizon_days:90});if(error)throw error;return data as any;}});
  const create=useMutation({mutationFn:async()=>{const {error}=await supabase.rpc("create_expense_commitment_atomic",{p_manager_id:managerId!,p_vendor_name:vendor,p_category:category,p_amount:Number(amount),p_due_date:due,p_description:description||null});if(error)throw error;},onSuccess:()=>{toast.success("Commitment created");setVendor("");setCategory("");setAmount("");setDescription("");q.refetch();},onError:(e:any)=>toast.error(e.message||"Could not create commitment")});
  const transition=useMutation({mutationFn:async({id,status}:{id:string;status:string})=>{const {error}=await supabase.rpc("transition_expense_commitment_atomic",{p_commitment_id:id,p_target_status:status,p_note:null});if(error)throw error;},onSuccess:()=>{toast.success("Commitment updated");q.refetch();},onError:(e:any)=>toast.error(e.message||"Could not update commitment")});
  const rows=q.data?.commitments??[];
  return <Card className="enterprise-card"><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="section-title flex items-center gap-2"><ClipboardList className="h-5 w-5"/> Expense Commitment & Payables Control</CardTitle><CardDescription>Approve future vendor obligations before they consume liquidity. Actual cash remains in the canonical ledger and expenditure records.</CardDescription></div><Button variant="outline" size="icon" onClick={()=>q.refetch()} disabled={q.isFetching} aria-label="Refresh commitments"><RefreshCw className={q.isFetching?"h-4 w-4 animate-spin":"h-4 w-4"}/></Button></div></CardHeader><CardContent className="space-y-5">
    <div className="grid gap-3 md:grid-cols-5"><Input placeholder="Vendor" value={vendor} onChange={e=>setVendor(e.target.value)}/><Input placeholder="Category" value={category} onChange={e=>setCategory(e.target.value)}/><Input type="number" min="0.01" placeholder="Amount" value={amount} onChange={e=>setAmount(e.target.value)}/><Input type="date" value={due} onChange={e=>setDue(e.target.value)}/><Button onClick={()=>create.mutate()} disabled={create.isPending||!managerId||!vendor||!category||Number(amount)<=0}>Add commitment</Button></div>
    <Input placeholder="Optional description" value={description} onChange={e=>setDescription(e.target.value)}/>
    {q.data&&<div className="grid gap-3 md:grid-cols-3"><div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">Approved commitments</p><p className="font-semibold tabular-nums">{fmt(q.data.approved_total)}</p></div><div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">Due in 90 days</p><p className="font-semibold tabular-nums">{fmt(q.data.approved_due_in_horizon)}</p></div><div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">Overdue approved</p><p className="font-semibold tabular-nums">{fmt(q.data.approved_overdue)}</p></div></div>}
    <div className="space-y-2">{rows.length===0?<p className="text-sm text-muted-foreground">No submitted or approved commitments in the current horizon.</p>:rows.map((r:any)=><div key={r.id} className="grid gap-2 rounded-lg border p-3 md:grid-cols-[1fr_130px_110px_auto] md:items-center"><div><p className="font-medium">{r.vendor_name}</p><p className="text-xs text-muted-foreground">{r.category}{r.description?` · ${r.description}`:""} · due {r.due_date}</p></div><p className="text-right font-semibold tabular-nums">{fmt(r.amount)}</p><Badge variant={r.status==="approved"?"default":"outline"}>{r.status}</Badge><div className="flex justify-end gap-2">{r.status==="draft"&&<Button size="sm" variant="outline" onClick={()=>transition.mutate({id:r.id,status:"submitted"})}>Submit</Button>}{r.status==="submitted"&&<Button size="sm" onClick={()=>transition.mutate({id:r.id,status:"approved"})}><CheckCircle2 className="mr-1 h-3 w-3"/>Approve</Button>}{r.status==="approved"&&<Button size="sm" variant="outline" onClick={()=>transition.mutate({id:r.id,status:"cancelled"})}>Cancel</Button>}</div></div>)}</div>
    <div className="rounded-lg border p-4 text-xs text-muted-foreground"><AlertTriangle className="mr-1 inline h-3 w-3"/> Approved commitments now flow into the treasury forecast as explicit cash obligations. Marking one settled is only a control status; it does not fabricate or replace the underlying bank/ledger transaction.</div>
  </CardContent></Card>;
}
