import { useMutation, useQuery } from "@tanstack/react-query";
import { Badge } from "@/shared/components/ui/badge";
import { Button } from "@/shared/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/shared/components/ui/card";
import { supabase } from "@/integrations/supabase/client";
import { useManagerScope } from "@/shared/hooks/useManagerScope";
import { AlertTriangle, CheckCircle2, RefreshCw, ShieldCheck, Timer, Truck } from "lucide-react";
import { toast } from "sonner";
import { formatDate } from "@/shared/lib/dateFormat";

export default function MaintenanceSlaVendorDispatchAssuranceCenter(){
  const {managerId}=useManagerScope();
  const q=useQuery({queryKey:["maintenance-sla-assurance",managerId],enabled:!!managerId,queryFn:async()=>{const {data,error}=await supabase.rpc("get_manager_maintenance_sla_assurance",{p_manager_id:managerId!,p_as_of:new Date().toISOString()});if(error)throw error;return data as any;}});
  const escalate=useMutation({mutationFn:async()=>{const {error}=await supabase.rpc("escalate_overdue_maintenance_sla_atomic",{p_manager_id:managerId!});if(error)throw error;},onSuccess:()=>{toast.success("Overdue maintenance SLAs escalated");q.refetch();},onError:(e:any)=>toast.error(e.message||"Could not escalate SLAs")});
  const verify=useMutation({mutationFn:async(id:string)=>{const {error}=await supabase.rpc("verify_maintenance_completion_atomic",{p_request_id:id,p_notes:"Verified from management maintenance assurance control."});if(error)throw error;},onSuccess:()=>{toast.success("Completion verified");q.refetch();},onError:(e:any)=>toast.error(e.message||"Could not verify completion")});
  const d=q.data; const rows=d?.work_orders??[];
  const stat=(label:string,value:any,icon:React.ReactNode)=> <div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground flex items-center gap-1">{icon}{label}</p><p className="font-semibold text-lg tabular-nums">{value}</p></div>;
  return <Card className="enterprise-card"><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="section-title flex items-center gap-2"><Timer className="h-5 w-5"/> Maintenance SLA, Vendor Dispatch & Completion Assurance</CardTitle><CardDescription>Control response deadlines, vendor dispatch, overdue escalation and management verification using the existing maintenance and procurement chain.</CardDescription></div><div className="flex gap-2"><Button variant="outline" onClick={()=>q.refetch()} size="icon" aria-label="Refresh maintenance SLA assurance"><RefreshCw className="h-4 w-4"/></Button><Button onClick={()=>escalate.mutate()} disabled={escalate.isPending||!managerId}>Escalate overdue</Button></div></div></CardHeader><CardContent className="space-y-5">
    {d&&<div className="grid gap-3 md:grid-cols-6">{stat("Open work orders",d.open_work_orders,<Truck className="h-3 w-3"/>)}{stat("Overdue SLA",d.overdue_sla,<AlertTriangle className="h-3 w-3"/>)}{stat("Due next 24h",d.due_next_24h,<Timer className="h-3 w-3"/>)}{stat("Awaiting dispatch",d.awaiting_dispatch,<Truck className="h-3 w-3"/>)}{stat("Awaiting verification",d.awaiting_completion_verification,<CheckCircle2 className="h-3 w-3"/>)}{stat("30d completion",`${d.completion_rate_30d}%`,<CheckCircle2 className="h-3 w-3"/>)}</div>}
    {rows.length===0?<p className="text-sm text-muted-foreground">No active or recently completed maintenance work orders require assurance.</p>:<div className="space-y-2">{rows.map((r:any)=><div key={r.id} className="grid gap-3 rounded-lg border p-3 md:grid-cols-[1fr_145px_145px_auto] md:items-center"><div className="min-w-0"><div className="flex items-center gap-2"><p className="font-medium truncate">{r.title}</p><Badge variant={r.sla_breached?"destructive":r.priority==="urgent"?"destructive":"outline"}>{r.sla_breached?"SLA breached":r.priority}</Badge></div><p className="text-xs text-muted-foreground truncate">{r.property_name}{r.unit_number?` · ${r.unit_number}`:""} · requested {formatDate(r.requested_date)}</p><p className="text-xs mt-1">{r.vendor_name?`Vendor: ${r.vendor_name}`:"No vendor"}{r.vendor_dispatched_at?" · Dispatched":" · Awaiting dispatch"}</p></div><div><p className="text-xs text-muted-foreground">SLA due</p><p className="text-sm">{r.sla_due_at?new Date(r.sla_due_at).toLocaleString():r.expected_completion_date?formatDate(r.expected_completion_date):"—"}</p><p className="text-xs text-muted-foreground">Escalation {r.sla_escalation_level}</p></div><div><p className="text-xs text-muted-foreground">Financial control</p><p className="text-sm">{r.commitment_status??"No commitment"}</p><p className="text-xs tabular-nums">Actual {Number(r.actual_spend??0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}</p></div><div className="flex justify-end">{r.status==="completed"&&!r.completion_verified_at?<Button size="sm" onClick={()=>verify.mutate(r.id)} disabled={verify.isPending}>Verify completion</Button>:<Badge variant={r.completion_verified_at?"default":"outline"}>{r.completion_verified_at?"Verified":r.vendor_name?"In delivery":"Needs dispatch"}</Badge>}</div></div>)}</div>}
    <div className="rounded-lg border p-4 text-xs text-muted-foreground"><ShieldCheck className="mr-1 inline h-3 w-3"/> Assurance chain: SLA → vendor dispatch → completion → management verification. Escalation changes operational priority only; financial actuals remain exclusively in the existing expenditure and double-entry ledger.</div>
  </CardContent></Card>;
}
