import { useQuery } from "@tanstack/react-query";
import { Badge } from "@/shared/components/ui/badge";
import { Button } from "@/shared/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/shared/components/ui/card";
import { Input } from "@/shared/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/shared/components/ui/select";
import { supabase } from "@/integrations/supabase/client";
import { useManagerScope } from "@/shared/hooks/useManagerScope";
import { Activity, AlertTriangle, RefreshCw, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { formatDate } from "@/shared/lib/dateFormat";

const conditionVariant=(v:string)=>v==="critical"||v==="poor"?"destructive":v==="fair"?"secondary":"outline";
const fmt=(v:unknown)=>Number(v??0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});

export default function MaintenanceAssetLifecycleCenter(){
  const {managerId}=useManagerScope();
  const q=useQuery({queryKey:["maintenance-asset-lifecycle",managerId],enabled:!!managerId,queryFn:async()=>{
    const {data,error}=await supabase.rpc("get_manager_maintenance_asset_lifecycle_control",{p_manager_id:managerId!,p_horizon_days:90});
    if(error) throw error; return data as any;
  }});
  const [reference,setReference]=useState(""); const [name,setName]=useState(""); const [type,setType]=useState(""); const [propertyId,setPropertyId]=useState(""); const [manufacturer,setManufacturer]=useState(""); const [model,setModel]=useState(""); const [installedOn,setInstalledOn]=useState(""); const [replacementDue,setReplacementDue]=useState(""); const [condition,setCondition]=useState("good"); const [criticality,setCriticality]=useState("medium"); const [saving,setSaving]=useState(false);
  const [assessmentAsset,setAssessmentAsset]=useState(""); const [assessmentCondition,setAssessmentCondition]=useState("good"); const [score,setScore]=useState(""); const [findings,setFindings]=useState(""); const [recommendation,setRecommendation]=useState("");
  const createAsset=async()=>{if(!managerId||!reference.trim()||!name.trim()||!type.trim())return; setSaving(true); try {const {error}=await supabase.rpc("create_maintenance_asset_atomic",{p_manager_id:managerId,p_asset_reference:reference.trim(),p_asset_name:name.trim(),p_asset_type:type.trim(),p_property_id:propertyId||null,p_manufacturer:manufacturer.trim()||null,p_model:model.trim()||null,p_installed_on:installedOn||null,p_replacement_due_date:replacementDue||null,p_condition_status:condition,p_criticality:criticality}); if(error)throw error; setReference("");setName("");setType("");setManufacturer("");setModel("");setInstalledOn("");setReplacementDue(""); await q.refetch();} finally{setSaving(false)}};
  const assess=async()=>{if(!assessmentAsset)return; const {error}=await supabase.rpc("record_maintenance_asset_condition_atomic",{p_asset_id:assessmentAsset,p_condition_status:assessmentCondition,p_condition_score:score?Number(score):null,p_findings:findings.trim()||null,p_recommended_action:recommendation.trim()||null}); if(error)throw error; setAssessmentAsset("");setFindings("");setRecommendation("");setScore("");await q.refetch();};
  const d=q.data as any; const assets=d?.assets??[];
  return <Card className="enterprise-card">
    <CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="section-title flex items-center gap-2"><Activity className="h-5 w-5"/> Maintenance Asset Register & Lifecycle Intelligence</CardTitle><CardDescription>Asset condition, service history, preventive coverage and replacement risk, linked to the existing maintenance and financial controls.</CardDescription></div><Button variant="outline" size="icon" onClick={()=>q.refetch()} aria-label="Refresh maintenance asset controls"><RefreshCw className="h-4 w-4"/></Button></div></CardHeader>
    <CardContent className="space-y-5">
      <div className="rounded-lg border p-4 space-y-3"><p className="font-medium">Register asset</p><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><Input placeholder="Asset reference" value={reference} onChange={e=>setReference(e.target.value)}/><Input placeholder="Asset name" value={name} onChange={e=>setName(e.target.value)}/><Input placeholder="Asset type / system" value={type} onChange={e=>setType(e.target.value)}/><Input placeholder="Property ID (optional)" value={propertyId} onChange={e=>setPropertyId(e.target.value)}/><Input placeholder="Manufacturer" value={manufacturer} onChange={e=>setManufacturer(e.target.value)}/><Input placeholder="Model" value={model} onChange={e=>setModel(e.target.value)}/><Input type="date" value={installedOn} onChange={e=>setInstalledOn(e.target.value)}/><Input type="date" value={replacementDue} onChange={e=>setReplacementDue(e.target.value)}/><Select value={condition} onValueChange={setCondition}><SelectTrigger><SelectValue placeholder="Condition"/></SelectTrigger><SelectContent>{["excellent","good","fair","poor","critical"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Select value={criticality} onValueChange={setCriticality}><SelectTrigger><SelectValue placeholder="Criticality"/></SelectTrigger><SelectContent>{["low","medium","high","critical"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><Button onClick={createAsset} disabled={saving||!reference.trim()||!name.trim()||!type.trim()}>Register asset</Button></div>
      {d&&<div className="grid gap-3 md:grid-cols-4"><div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">Active assets</p><p className="font-semibold">{d.active_assets}</p></div><div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">Poor / critical</p><p className="font-semibold">{d.poor_or_critical}</p></div><div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">Replacement due ≤90d</p><p className="font-semibold">{d.replacement_due}</p></div><div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">Without preventive plan</p><p className="font-semibold">{d.without_preventive_plan}</p></div></div>}
      {assets.length>0&&<div className="rounded-lg border p-4 space-y-3"><p className="font-medium">Record condition assessment</p><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><Select value={assessmentAsset} onValueChange={setAssessmentAsset}><SelectTrigger><SelectValue placeholder="Select asset"/></SelectTrigger><SelectContent>{assets.map((a:any)=><SelectItem key={a.id} value={a.id}>{a.asset_reference} · {a.asset_name}</SelectItem>)}</SelectContent></Select><Select value={assessmentCondition} onValueChange={setAssessmentCondition}><SelectTrigger><SelectValue placeholder="Condition"/></SelectTrigger><SelectContent>{["excellent","good","fair","poor","critical"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Input type="number" min="0" max="100" placeholder="Condition score" value={score} onChange={e=>setScore(e.target.value)}/><Input placeholder="Recommended action" value={recommendation} onChange={e=>setRecommendation(e.target.value)}/><Input className="md:col-span-2 lg:col-span-4" placeholder="Findings" value={findings} onChange={e=>setFindings(e.target.value)}/></div><Button variant="outline" onClick={assess} disabled={!assessmentAsset}>Save assessment</Button></div>}
      <div className="space-y-2">{assets.length===0?<p className="text-sm text-muted-foreground">No active maintenance assets are registered.</p>:assets.map((a:any)=><div key={a.id} className="grid gap-3 rounded-lg border p-3 md:grid-cols-[1fr_150px_150px_auto] md:items-center"><div className="min-w-0"><div className="flex items-center gap-2"><p className="font-medium truncate">{a.asset_reference} · {a.asset_name}</p><Badge variant={conditionVariant(a.condition_status) as any}>{a.condition_status}</Badge><Badge variant="outline">{a.criticality}</Badge></div><p className="text-xs text-muted-foreground truncate">{a.asset_type}{a.manufacturer?` · ${a.manufacturer}`:""}{a.model?` ${a.model}`:""}</p><p className="text-xs mt-1">{a.maintenance_count} maintenance event(s) · {a.preventive_plan_count} preventive plan(s) · spend {fmt(a.maintenance_spend)}</p></div><div><p className="text-xs text-muted-foreground">Last service</p><p className="text-sm">{a.last_maintenance_date?formatDate(a.last_maintenance_date):"—"}</p><p className="text-xs text-muted-foreground">Assessment {a.last_assessment_date?formatDate(a.last_assessment_date):"—"}</p></div><div><p className="text-xs text-muted-foreground">Replacement</p><p className="text-sm">{a.replacement_due_date?formatDate(a.replacement_due_date):"Not set"}</p><p className="text-xs text-muted-foreground">{a.days_to_replacement==null?"":a.days_to_replacement<0?`${Math.abs(a.days_to_replacement)} day(s) overdue`:`${a.days_to_replacement} day(s)`}</p></div><Badge variant={a.condition_status==="critical"||a.condition_status==="poor"||a.days_to_replacement<0?"destructive":"outline"}>{a.condition_status==="critical"||a.condition_status==="poor"?<><AlertTriangle className="mr-1 h-3 w-3"/>Risk</>:a.days_to_replacement<0?"Replacement overdue":"Covered"}</Badge></div>)}</div>
      <div className="rounded-lg border p-4 text-xs text-muted-foreground"><ShieldCheck className="mr-1 inline h-3 w-3"/> Asset intelligence is an operational layer: work orders remain canonical for maintenance history, expenditures remain canonical for actual cost, and the existing preventive/SLA/procurement/ledger controls remain authoritative.</div>
    </CardContent>
  </Card>;
}
