import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Banknote, CheckCircle2, LockKeyhole, RefreshCw, Plus } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useManagerScope } from "@/shared/hooks/useManagerScope";
import { useCurrency } from "@/shared/hooks/useCurrency";
import { Card, CardContent, CardHeader, CardTitle } from "@/shared/components/ui/card";
import { Button } from "@/shared/components/ui/button";
import { Badge } from "@/shared/components/ui/badge";
import { Input } from "@/shared/components/ui/input";
import { toast } from "sonner";

export function OwnerPayoutSettlementCenter() {
  const { managerId } = useManagerScope();
  const { formatCurrency } = useCurrency();
  const queryClient = useQueryClient();
  const [periodId, setPeriodId] = useState("");
  const [selected, setSelected] = useState<string[]>([]);
  const [reference, setReference] = useState("");
  const batches = useQuery({ queryKey: ["owner-payout-settlement", managerId], enabled: !!managerId, queryFn: async () => { const { data, error } = await supabase.rpc("get_manager_owner_payout_settlement" as any, { p_manager_id: managerId }); if (error) throw error; return (data ?? { batches: [] }) as any; } });
  const periods = useQuery({ queryKey: ["closed-financial-periods", managerId], enabled: !!managerId, queryFn: async () => { const { data, error } = await supabase.from("financial_close_periods").select("id,period_start,period_end,status").eq("manager_id", managerId).eq("status", "closed").order("period_end", { ascending: false }).limit(12); if (error) throw error; return data ?? []; } });
  const payouts = useQuery({ queryKey: ["approved-owner-payouts", managerId, periodId], enabled: !!managerId && !!periodId, queryFn: async () => { const period = (periods.data ?? []).find((p:any)=>p.id===periodId); if (!period) return []; const { data, error } = await supabase.from("payout_requests").select("id,property_id,amount,management_fee_amt,net_amount,period_start,period_end,status").eq("manager_id", managerId).eq("status", "approved").gte("period_start", period.period_start).lte("period_end", period.period_end).order("period_end", { ascending: false }); if (error) throw error; return data ?? []; } });
  const create = useMutation({ mutationFn: async () => { const { data, error } = await supabase.rpc("create_owner_payout_batch_atomic" as any, { p_manager_id: managerId, p_close_period_id: periodId, p_payout_ids: selected }); if (error) throw error; return data; }, onSuccess: () => { toast.success("Owner settlement batch created."); setSelected([]); setPeriodId(""); queryClient.invalidateQueries({ queryKey: ["owner-payout-settlement", managerId] }); }, onError: (e:Error)=>toast.error(e.message || "Could not create settlement batch.") });
  const transition = useMutation({ mutationFn: async ({ id, status }: {id:string;status:string}) => { const { data, error } = await supabase.rpc("transition_owner_payout_batch_atomic" as any, { p_batch_id:id, p_target_status:status, p_settlement_reference: status === "settled" ? reference.trim() : null }); if (error) throw error; return data; }, onSuccess:()=>{ toast.success("Settlement state updated."); setReference(""); queryClient.invalidateQueries({queryKey:["owner-payout-settlement",managerId]}); }, onError:(e:Error)=>toast.error(e.message || "Settlement update failed.") });
  if (batches.isLoading) return <div className="h-56 rounded-xl border border-border bg-card animate-pulse" aria-busy="true" />;
  const rows=batches.data?.batches??[];
  return <Card className="border-border/80 shadow-[0_8px_28px_-22px_rgb(13_39_68/0.28)]">
    <CardHeader className="pb-3"><div className="flex items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2 text-base"><Banknote className="h-4 w-4"/>Owner Payout & Settlement</CardTitle><p className="mt-1 text-xs text-muted-foreground">Settle approved owner payouts only after the financial period is closed.</p></div><Button variant="outline" size="icon" onClick={()=>batches.refetch()} disabled={batches.isFetching} aria-label="Refresh settlements"><RefreshCw className={batches.isFetching?"h-4 w-4 animate-spin":"h-4 w-4"}/></Button></div></CardHeader>
    <CardContent className="space-y-4">
      <div className="rounded-lg border border-border p-3"><div className="flex items-center gap-2 text-sm font-semibold"><Plus className="h-4 w-4"/>Create settlement batch</div><p className="mt-1 text-xs text-muted-foreground">Select a closed period, then select approved payouts that have not already been batched.</p><div className="mt-3 flex flex-wrap gap-2">{(periods.data??[]).map((p:any)=><Button key={p.id} size="sm" variant={periodId===p.id?"default":"outline"} onClick={()=>{setPeriodId(p.id);setSelected([])}}>{p.period_start} → {p.period_end}</Button>)}</div>{periodId&&<div className="mt-3 space-y-2">{payouts.isLoading?<p className="text-xs text-muted-foreground">Loading approved payouts…</p>:payouts.data?.length?<>{payouts.data.map((p:any)=><label key={p.id} className="flex items-center justify-between gap-3 rounded-md border border-border px-3 py-2 text-xs"><span className="flex items-center gap-2"><input type="checkbox" checked={selected.includes(p.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,p.id]:v.filter(id=>id!==p.id))}/><span>{p.period_start} → {p.period_end}</span></span><span className="font-semibold tabular-nums">{formatCurrency(Number(p.amount||0))}</span></label>)}<Button size="sm" onClick={()=>create.mutate()} disabled={!selected.length||create.isPending}>{create.isPending?"Creating…":"Create batch"}</Button></>:<p className="text-xs text-muted-foreground">No approved payouts available for this closed period.</p>}</div>}</div>
      {rows.length===0?<div className="rounded-lg border border-dashed p-6 text-center"><p className="text-sm font-medium">No settlement batches yet</p><p className="mt-1 text-xs text-muted-foreground">Approved payouts will appear here once batched.</p></div>:rows.slice(0,8).map((b:any)=><div key={b.id} className="rounded-lg border border-border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><div className="flex items-center gap-2 text-sm font-semibold"><LockKeyhole className="h-3.5 w-3.5"/>Closed period {b.period_start} → {b.period_end}</div><p className="mt-1 text-[11px] text-muted-foreground">{b.item_count} payout(s) · {new Date(b.created_at).toLocaleDateString()}</p></div><Badge variant={b.status==="settled"?"default":b.status==="rejected"?"destructive":"outline"}>{b.status}</Badge></div><div className="mt-3 grid grid-cols-3 gap-2"><Metric label="Gross" value={formatCurrency(Number(b.gross_amount||0))}/><Metric label="Fees" value={formatCurrency(Number(b.fee_amount||0))}/><Metric label="Net" value={formatCurrency(Number(b.net_amount||0))}/></div><div className="mt-3 flex flex-wrap gap-2">{b.status==="draft"&&<Button size="sm" onClick={()=>transition.mutate({id:b.id,status:"approved"})}>Approve batch</Button>}{b.status==="approved"&&<Button size="sm" variant="outline" onClick={()=>transition.mutate({id:b.id,status:"processing"})}>Start settlement</Button>}{b.status==="processing"&&<div className="flex gap-2"><Input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Settlement reference" className="h-8 w-48 text-xs"/><Button size="sm" onClick={()=>transition.mutate({id:b.id,status:"settled"})} disabled={!reference.trim()||transition.isPending}>Confirm settled</Button></div>}{b.status==="settled"&&<span className="inline-flex items-center gap-1 text-xs text-muted-foreground"><CheckCircle2 className="h-3.5 w-3.5"/>Settled {b.settlement_reference?`· ${b.settlement_reference}`:""}</span>}</div></div>)}
    </CardContent></Card>;
}
const Metric=({label,value}:{label:string;value:string})=><div className="rounded-md bg-muted/30 px-2 py-1.5"><p className="text-[9px] uppercase tracking-wide text-muted-foreground">{label}</p><p className="text-sm font-semibold tabular-nums">{value}</p></div>;
