import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { AlertTriangle, CalendarCheck, RefreshCw, ShieldCheck } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useManagerScope } from "@/shared/hooks/useManagerScope";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/shared/components/ui/card";
import { Button } from "@/shared/components/ui/button";
import { Badge } from "@/shared/components/ui/badge";
import { Input } from "@/shared/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/shared/components/ui/select";
import { Textarea } from "@/shared/components/ui/textarea";
import { toast } from "sonner";

const variant=(v:string)=>v==="critical"||v==="expired"||v==="overdue"?"destructive":v==="high"||v==="attention"?"secondary":"outline";
export default function PropertySafetyRegulatoryRiskCenter(){
 const {managerId}=useManagerScope(); const q=useQuery({queryKey:["property-safety-risk-control",managerId],enabled:!!managerId,queryFn:async()=>{const {data,error}=await supabase.rpc("get_manager_property_safety_risk_control",{p_manager_id:managerId!,p_horizon_days:60});if(error)throw error;return data as any;}});
 const [propertyId,setPropertyId]=useState(""); const [type,setType]=useState(""); const [number,setNumber]=useState(""); const [authority,setAuthority]=useState(""); const [expires,setExpires]=useState(""); const [saving,setSaving]=useState(false);
 const [riskProperty,setRiskProperty]=useState(""); const [riskTitle,setRiskTitle]=useState(""); const [category,setCategory]=useState(""); const [severity,setSeverity]=useState("medium"); const [target,setTarget]=useState(""); const [notes,setNotes]=useState("");
 const certificate=async()=>{if(!managerId||!propertyId.trim()||!type.trim())return;setSaving(true);try{const {error}=await supabase.rpc("upsert_property_safety_certificate_atomic",{p_manager_id:managerId,p_property_id:propertyId.trim(),p_certificate_type:type.trim(),p_certificate_number:number.trim()||null,p_issuing_authority:authority.trim()||null,p_expires_on:expires||null});if(error)throw error;setPropertyId("");setType("");setNumber("");setAuthority("");setExpires("");await q.refetch();toast.success("Safety certificate recorded.")}catch(e){toast.error((e as Error).message)}finally{setSaving(false)}};
 const risk=async()=>{if(!managerId||!riskProperty.trim()||!riskTitle.trim()||!category.trim())return;setSaving(true);try{const {error}=await supabase.rpc("create_property_risk_atomic",{p_manager_id:managerId,p_property_id:riskProperty.trim(),p_risk_title:riskTitle.trim(),p_risk_category:category.trim(),p_severity:severity,p_target_date:target||null,p_remediation_notes:notes.trim()||null});if(error)throw error;setRiskProperty("");setRiskTitle("");setCategory("");setTarget("");setNotes("");await q.refetch();toast.success("Risk entered into the remediation register.")}catch(e){toast.error((e as Error).message)}finally{setSaving(false)}};
 const d=q.data as any; const certs=d?.certificates??[], risks=d?.risks??[];
 return <Card className="enterprise-card"><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="section-title flex items-center gap-2"><ShieldCheck className="h-5 w-5"/> Property Safety, Regulatory Certification & Risk Remediation</CardTitle><CardDescription>Track statutory certificates and safety risks, then drive remediation through the existing inspection, asset, maintenance, SLA, procurement and financial controls.</CardDescription></div><Button variant="outline" size="icon" onClick={()=>q.refetch()} aria-label="Refresh property safety controls"><RefreshCw className="h-4 w-4"/></Button></div></CardHeader><CardContent className="space-y-5">
 <div className="grid gap-3 md:grid-cols-3 lg:grid-cols-6">{[["Active certificates",d?.active_certificates],["Expiring ≤60d",d?.expiring_certificates],["Expired",d?.expired_certificates],["Open risks",d?.open_risks],["Critical risks",d?.critical_risks],["Overdue risks",d?.overdue_risks]].map(([l,v])=><div key={l as string} className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">{l}</p><p className="font-semibold tabular-nums">{v??0}</p></div>)}</div>
 <div className="rounded-lg border p-4 space-y-3"><p className="font-medium">Record safety / statutory certificate</p><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-5"><Input placeholder="Property ID" value={propertyId} onChange={e=>setPropertyId(e.target.value)}/><Input placeholder="Certificate type" value={type} onChange={e=>setType(e.target.value)}/><Input placeholder="Certificate number" value={number} onChange={e=>setNumber(e.target.value)}/><Input placeholder="Issuing authority" value={authority} onChange={e=>setAuthority(e.target.value)}/><Input type="date" value={expires} onChange={e=>setExpires(e.target.value)}/></div><Button onClick={certificate} disabled={saving||!propertyId.trim()||!type.trim()}>Record certificate</Button></div>
 <div className="rounded-lg border p-4 space-y-3"><p className="font-medium">Register safety / regulatory risk</p><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-5"><Input placeholder="Property ID" value={riskProperty} onChange={e=>setRiskProperty(e.target.value)}/><Input placeholder="Risk title" value={riskTitle} onChange={e=>setRiskTitle(e.target.value)}/><Input placeholder="Risk category" value={category} onChange={e=>setCategory(e.target.value)}/><Select value={severity} onValueChange={setSeverity}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["low","medium","high","critical"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Input type="date" value={target} onChange={e=>setTarget(e.target.value)}/><Textarea className="md:col-span-2 lg:col-span-5" placeholder="Remediation notes" value={notes} onChange={e=>setNotes(e.target.value)}/></div><Button onClick={risk} disabled={saving||!riskProperty.trim()||!riskTitle.trim()||!category.trim()}>Register risk</Button></div>
 <div className="space-y-2">{certs.length===0?<p className="text-sm text-muted-foreground">No safety certificates recorded.</p>:certs.map((c:any)=><div key={c.id} className="grid gap-3 rounded-lg border p-3 md:grid-cols-[1fr_150px_130px_auto] md:items-center"><div><p className="font-medium">{c.certificate_type}</p><p className="text-xs text-muted-foreground">Property {c.property_id}{c.certificate_number?` · ${c.certificate_number}`:""}{c.authority?` · ${c.authority}`:""}</p></div><div><p className="text-xs text-muted-foreground">Expiry</p><p className="text-sm">{c.expires_on||"Not set"}</p></div><div><p className="text-xs text-muted-foreground">Evidence</p><p className="text-sm">{c.has_evidence?"Linked":"Missing"}</p></div><Badge variant={variant(c.status) as any}>{c.status}{c.days_to_expiry!=null?` · ${c.days_to_expiry}d`:""}</Badge></div>)}</div>
 <div className="space-y-2">{risks.length===0?<p className="text-sm text-muted-foreground">No property safety risks recorded.</p>:risks.map((r:any)=><div key={r.id} className="grid gap-3 rounded-lg border p-3 md:grid-cols-[1fr_130px_130px_auto] md:items-center"><div><p className="font-medium">{r.risk_title}</p><p className="text-xs text-muted-foreground">Property {r.property_id} · {r.risk_category}{r.maintenance_request_id?" · remediation work order linked":""}</p></div><Badge variant={variant(r.severity) as any}>{r.severity}</Badge><div><p className="text-xs text-muted-foreground">Target</p><p className="text-sm">{r.target_date||"Not set"}</p></div><Badge variant={r.status==="open"&&r.days_to_target<0?"destructive":"outline"}>{r.status}{r.days_to_target!=null?` · ${r.days_to_target}d`:""}</Badge></div>)}</div>
 <div className="rounded-lg border p-4 text-xs text-muted-foreground"><CalendarCheck className="mr-1 inline h-3 w-3"/> Certificates are evidence controls; risks are remediation controls. Existing inspection findings remain the source for inspection evidence, maintenance requests remain the canonical corrective-work source, and accounting remains the existing ledger.</div>
 </CardContent></Card>;
}
