import { useQuery } from "@tanstack/react-query";
import { Badge } from "@/shared/components/ui/badge";
import { Button } from "@/shared/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/shared/components/ui/card";
import { Input } from "@/shared/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/shared/components/ui/select";
import { supabase } from "@/integrations/supabase/client";
import { useManagerScope } from "@/shared/hooks/useManagerScope";
import { ClipboardCheck, RefreshCw, ShieldCheck, AlertTriangle } from "lucide-react";
import { useState } from "react";
import { formatDate } from "@/shared/lib/dateFormat";

const statusVariant=(s:string)=>s==="non_compliant"||s==="fail"?"destructive":s==="attention"?"secondary":"outline";
export default function PropertyInspectionComplianceAssuranceCenter(){
  const {managerId}=useManagerScope();
  const q=useQuery({queryKey:["property-inspection-compliance-assurance",managerId],enabled:!!managerId,queryFn:async()=>{const {data,error}=await supabase.rpc("get_manager_property_inspection_compliance_control",{p_manager_id:managerId!,p_horizon_days:30});if(error)throw error;return data as any;}});
  const [name,setName]=useState("");const [type,setType]=useState("periodic");const [frequency,setFrequency]=useState("90");const [due,setDue]=useState(new Date().toISOString().slice(0,10));const [saving,setSaving]=useState(false);const [generating,setGenerating]=useState(false);
  const [findingRun,setFindingRun]=useState("");const [findingKey,setFindingKey]=useState("");const [findingLabel,setFindingLabel]=useState("");const [findingResult,setFindingResult]=useState("pass");const [findingNotes,setFindingNotes]=useState("");const [raiseMaintenance,setRaiseMaintenance]=useState(false);const [maintenanceTitle,setMaintenanceTitle]=useState("");const [maintenanceDescription,setMaintenanceDescription]=useState("");const [findingSaving,setFindingSaving]=useState(false);
  const [complianceTitle,setComplianceTitle]=useState("");const [authority,setAuthority]=useState("");const [referenceCode,setReferenceCode]=useState("");const [complianceStatus,setComplianceStatus]=useState("attention");const [nextReview,setNextReview]=useState("");const [complianceSaving,setComplianceSaving]=useState(false);
  const createProgram=async()=>{if(!managerId||!name.trim())return;setSaving(true);try{const {error}=await supabase.rpc("create_property_inspection_program_atomic",{p_manager_id:managerId,p_name:name.trim(),p_inspection_type:type,p_frequency_days:Number(frequency),p_next_due_date:due,p_checklist:[]});if(error)throw error;setName("");await q.refetch();}finally{setSaving(false)}};
  const generate=async()=>{if(!managerId)return;setGenerating(true);try{const {error}=await supabase.rpc("generate_due_property_inspections_atomic",{p_manager_id:managerId,p_horizon_days:30});if(error)throw error;await q.refetch()}finally{setGenerating(false)}};
  const saveFinding=async()=>{if(!findingRun||!findingKey.trim()||!findingLabel.trim())return;setFindingSaving(true);try{const {error}=await supabase.rpc("record_property_inspection_finding_atomic",{p_inspection_run_id:findingRun,p_checklist_key:findingKey.trim(),p_checklist_label:findingLabel.trim(),p_result:findingResult,p_notes:findingNotes.trim()||null,p_evidence_urls:[],p_asset_id:null,p_raise_maintenance:raiseMaintenance,p_maintenance_title:maintenanceTitle.trim()||null,p_maintenance_description:maintenanceDescription.trim()||null,p_priority:findingResult==="fail"?"high":"medium",p_category:"maintenance"});if(error)throw error;setFindingKey("");setFindingLabel("");setFindingNotes("");setMaintenanceTitle("");setMaintenanceDescription("");await q.refetch()}finally{setFindingSaving(false)}};
  const saveCompliance=async()=>{if(!managerId||!complianceTitle.trim())return;setComplianceSaving(true);try{const {error}=await supabase.rpc("upsert_property_compliance_requirement_atomic",{p_manager_id:managerId,p_title:complianceTitle.trim(),p_authority:authority.trim()||null,p_reference_code:referenceCode.trim()||null,p_status:complianceStatus,p_next_review_date:nextReview||null});if(error)throw error;setComplianceTitle("");setAuthority("");setReferenceCode("");setNextReview("");await q.refetch()}finally{setComplianceSaving(false)}};
  const d=q.data as any;const programs=d?.programs??[];const runs=d?.runs??[];const requirements=d?.requirements??[];const risks=d?.asset_risks??[];
  return <Card className="enterprise-card"><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="section-title flex items-center gap-2"><ClipboardCheck className="h-5 w-5"/> Property Inspections, Compliance & Condition Assurance</CardTitle><CardDescription>Scheduled inspections, checklist findings, compliance obligations and condition risks feed the existing asset, maintenance, SLA, procurement and financial controls.</CardDescription></div><div className="flex gap-2"><Button variant="outline" onClick={generate} disabled={generating}>Generate due inspections</Button><Button variant="outline" size="icon" onClick={()=>q.refetch()} aria-label="Refresh inspection controls"><RefreshCw className="h-4 w-4"/></Button></div></div></CardHeader><CardContent className="space-y-5">
    <div className="rounded-lg border p-4 space-y-3"><p className="font-medium">Create inspection programme</p><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><Input placeholder="Programme name" value={name} onChange={e=>setName(e.target.value)}/><Select value={type} onValueChange={setType}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["periodic","safety","compliance","handover","pre_lease","post_incident"].map(x=><SelectItem key={x} value={x}>{x.replace("_"," ")}</SelectItem>)}</SelectContent></Select><Input type="number" min="1" placeholder="Frequency (days)" value={frequency} onChange={e=>setFrequency(e.target.value)}/><Input type="date" value={due} onChange={e=>setDue(e.target.value)}/></div><Button onClick={createProgram} disabled={saving||!name.trim()}>Create programme</Button></div>
    {d&&<div className="grid gap-3 md:grid-cols-5"><div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">Active programmes</p><p className="font-semibold">{d.active_programs}</p></div><div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">Due runs ≤30d</p><p className="font-semibold">{d.due_runs}</p></div><div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">Open findings</p><p className="font-semibold">{d.open_findings}</p></div><div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">Non-compliant</p><p className="font-semibold">{d.non_compliant}</p></div><div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">Reviews ≤30d</p><p className="font-semibold">{d.compliance_due}</p></div></div>}
    {runs.length>0&&<div className="rounded-lg border p-4 space-y-3"><p className="font-medium">Record inspection finding</p><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><Select value={findingRun} onValueChange={setFindingRun}><SelectTrigger><SelectValue placeholder="Inspection run"/></SelectTrigger><SelectContent>{runs.map((r:any)=><SelectItem key={r.id} value={r.id}>{r.program_name} · {formatDate(r.scheduled_for)}</SelectItem>)}</SelectContent></Select><Input placeholder="Checklist key" value={findingKey} onChange={e=>setFindingKey(e.target.value)}/><Input placeholder="Checklist item / label" value={findingLabel} onChange={e=>setFindingLabel(e.target.value)}/><Select value={findingResult} onValueChange={setFindingResult}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["pass","attention","fail","not_applicable"].map(x=><SelectItem key={x} value={x}>{x.replace("_"," ")}</SelectItem>)}</SelectContent></Select><Input className="md:col-span-2" placeholder="Finding notes" value={findingNotes} onChange={e=>setFindingNotes(e.target.value)}/>{findingResult!=="pass"&&findingResult!=="not_applicable"&&<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={raiseMaintenance} onChange={e=>setRaiseMaintenance(e.target.checked)}/> Raise canonical maintenance work order</label>}</div>{raiseMaintenance&&<div className="grid gap-3 md:grid-cols-2"><Input placeholder="Maintenance title" value={maintenanceTitle} onChange={e=>setMaintenanceTitle(e.target.value)}/><Input placeholder="Maintenance description" value={maintenanceDescription} onChange={e=>setMaintenanceDescription(e.target.value)}/></div>}<Button variant="outline" onClick={saveFinding} disabled={findingSaving||!findingRun||!findingKey.trim()||!findingLabel.trim()}>Save finding</Button></div>}
    <div className="space-y-2"><p className="font-medium">Inspection programmes</p>{programs.length===0?<p className="text-sm text-muted-foreground">No inspection programmes configured.</p>:programs.map((p:any)=><div key={p.id} className="grid gap-3 rounded-lg border p-3 md:grid-cols-[1fr_150px_150px_auto] md:items-center"><div><p className="font-medium">{p.name}</p><p className="text-xs text-muted-foreground">{p.inspection_type} · every {p.frequency_days} days · {p.run_count} run(s)</p></div><div><p className="text-xs text-muted-foreground">Next due</p><p className="text-sm">{formatDate(p.next_due_date)}</p></div><div><p className="text-xs text-muted-foreground">Timing</p><p className="text-sm">{p.days_to_due<0?`${Math.abs(p.days_to_due)} day(s) overdue`:p.days_to_due===0?"Due today":`${p.days_to_due} day(s)`}</p></div><Badge variant={p.days_to_due<0?"destructive":"outline"}>{p.days_to_due<0?"Overdue":"Scheduled"}</Badge></div>)}</div>
    <div className="space-y-2"><p className="font-medium">Scheduled / active runs</p>{runs.length===0?<p className="text-sm text-muted-foreground">No generated inspection runs.</p>:runs.slice(0,8).map((r:any)=><div key={r.id} className="grid gap-3 rounded-lg border p-3 md:grid-cols-[1fr_130px_130px_auto] md:items-center"><div><p className="font-medium">{r.program_name}</p><p className="text-xs text-muted-foreground">{r.finding_count} finding(s) · {r.fail_count} failed</p></div><div><p className="text-xs text-muted-foreground">Scheduled</p><p className="text-sm">{formatDate(r.scheduled_for)}</p></div><Badge variant={r.status==="in_progress"?"secondary":"outline"}>{r.status}</Badge><Badge variant={r.fail_count>0?"destructive":"outline"}>{r.fail_count>0?"Defects found":"Ready"}</Badge></div>)}</div>
    <div className="rounded-lg border p-4 space-y-3"><p className="font-medium">Register compliance obligation</p><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><Input placeholder="Requirement title" value={complianceTitle} onChange={e=>setComplianceTitle(e.target.value)}/><Input placeholder="Authority" value={authority} onChange={e=>setAuthority(e.target.value)}/><Input placeholder="Reference code" value={referenceCode} onChange={e=>setReferenceCode(e.target.value)}/><Select value={complianceStatus} onValueChange={setComplianceStatus}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["compliant","attention","non_compliant","not_applicable"].map(x=><SelectItem key={x} value={x}>{x.replace("_"," ")}</SelectItem>)}</SelectContent></Select><Input type="date" value={nextReview} onChange={e=>setNextReview(e.target.value)} placeholder="Next review"/></div><Button variant="outline" onClick={saveCompliance} disabled={complianceSaving||!complianceTitle.trim()}>Register obligation</Button></div>
    <div className="space-y-2"><p className="font-medium">Compliance obligations</p>{requirements.length===0?<p className="text-sm text-muted-foreground">No property compliance obligations registered.</p>:requirements.slice(0,10).map((c:any)=><div key={c.id} className="grid gap-3 rounded-lg border p-3 md:grid-cols-[1fr_140px_140px_auto] md:items-center"><div><p className="font-medium">{c.title}</p><p className="text-xs text-muted-foreground">{c.authority||"Authority not specified"}{c.reference_code?` · ${c.reference_code}`:""} {c.has_evidence?"· Evidence linked":"· Evidence gap"}</p></div><div><p className="text-xs text-muted-foreground">Status</p><Badge variant={statusVariant(c.status) as any}>{c.status.replace("_"," ")}</Badge></div><div><p className="text-xs text-muted-foreground">Next review</p><p className="text-sm">{c.next_review_date?formatDate(c.next_review_date):"Not set"}</p></div><Badge variant={!c.has_evidence||c.status==="non_compliant"?"destructive":"outline"}>{!c.has_evidence?"Evidence gap":c.status==="non_compliant"?"Action needed":"Controlled"}</Badge></div>)}</div>
    {risks.length>0&&<div className="rounded-lg border p-4 space-y-2"><p className="font-medium flex items-center gap-2"><AlertTriangle className="h-4 w-4"/> High-risk assets seen by inspection intelligence</p>{risks.slice(0,6).map((a:any)=><div key={a.id} className="flex items-center justify-between gap-3 text-sm"><span>{a.asset_reference} · {a.asset_name}</span><span className="text-muted-foreground">{a.condition_status} · {a.inspection_findings} finding(s)</span></div>)}</div>}
    <div className="rounded-lg border p-4 text-xs text-muted-foreground"><ShieldCheck className="mr-1 inline h-3 w-3"/> Assurance chain: programme → inspection run → checklist finding/evidence → optional canonical maintenance work order → existing asset/SLA/vendor/procurement controls. Compliance evidence remains linked to the existing governed document register.</div>
  </CardContent></Card>;
}
